export const USER_GEOLOCATION = 'USER_GEOLOCATION';
export const WEATHER_INFORMATION = 'WEATHER_INFORMATION';
export const SEARCH = 'SEARCH';
export const NO_SEARCH = 'NO_SEARCH';
export const LOADING_DATA = 'LOADING_DATA';
export const WEATHER_REPORT = 'WEATHER_REPORT';